// 腳本自動刷新
export default {
  BgFixed: [
    { props: 'src', type: 'string', optional: false },
    { props: 'minHeight', type: 'string | number', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  BgMarquee: [
    { props: 'src', type: 'string', optional: true },
    { props: 'seconds', type: 'string | number', optional: true },
    { props: 'move', type: '"left" | "right" | "up" | "down"', optional: true },
    { props: 'class', type: 'string', optional: true },
  ],
  Btn01: [
    { props: 'shadow', type: 'string', optional: true },
    { props: 'class', type: 'string', optional: true },
    { props: 'href', type: 'string', optional: false },
    { props: 'color', type: 'string', optional: true },
    { props: 'backgroundColor', type: 'string', optional: true },
    { props: 'blank', type: 'boolean', optional: true },
  ],
  Flex: [
    { props: 'wrap', type: 'boolean', optional: true },
    { props: 'flexReverse', type: 'boolean', optional: true },
    { props: 'mobile', type: '"3xl" | "2xl" | "xl" | "lg" | "md" | "sm" | "xs" | "2xs" | "none" | "inherit"', optional: true },
    { props: 'mobileItem', type: '"stretch" | "start" | "center" | "end" | "baseline"', optional: true },
    { props: 'mobileJustify', type: '"start" | "center" | "end" | "between" | "around" | "evenly" | "space-between" | "space-around" | "space-evenly"', optional: true },
    { props: 'mobileReverse', type: 'boolean', optional: true },
    { props: 'reverse', type: 'boolean', optional: true },
    { props: 'item', type: '"stretch" | "start" | "center" | "end" | "baseline"', optional: true },
    { props: 'justify', type: '"start" | "center" | "end" | "between" | "around" | "evenly" | "space-between" | "space-around" | "space-evenly"', optional: true },
    { props: 'gap', type: 'string | number', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  IconOrbitText: [
    { props: 'seconds', type: 'string | number', optional: true },
    { props: 'reverse', type: 'boolean', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  Img: [
    { props: 'scale', type: 'boolean', optional: true },
    { props: 'cover', type: 'boolean', optional: true },
    { props: 'class', type: 'string', optional: true },
    { props: 'src', type: 'string', optional: false },
  ],
  ImgHoverTranslate: [
    { props: 'src', type: 'string', optional: false },
    { props: 'width', type: 'number', optional: false },
    { props: 'height', type: 'number', optional: false },
    { props: 'seconds', type: 'string | number', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  LeftLineList: [
    { props: 'item', type: '"stretch" | "start" | "center" | "end"', optional: true },
    { props: 'gap', type: 'string | number', optional: true },
    { props: 'lineGap', type: 'string | number', optional: true },
    { props: 'trimStart', type: 'boolean', optional: true },
    { props: 'trimEnd', type: 'boolean', optional: true },
    { props: 'mobile', type: '"lg" | "md" | "sm" | "xs" | "2xs" | "none"', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  Marquee: [
    { props: 'seconds', type: 'string | number', optional: true },
    { props: 'move', type: '"left" | "right" | "up" | "down"', optional: true },
    { props: 'hover', type: 'boolean', optional: true },
    { props: 'src', type: 'string', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  prototype: [
    { props: 'item', type: '"stretch" | "start" | "center" | "end"', optional: true },
    { props: 'gap', type: 'string | number', optional: true },
    { props: 'lineGap', type: 'string | number', optional: true },
    { props: 'trimStart', type: 'boolean', optional: true },
    { props: 'trimEnd', type: 'boolean', optional: true },
    { props: 'mobile', type: '"lg" | "md" | "sm" | "xs" | "2xs" | "none"', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  RevealCard: [
    { props: 'background', type: 'string', optional: true },
    { props: 'backgroundHover', type: 'string', optional: true },
    { props: 'mobile', type: '"2xl" | "md" | "sm" | "xs" | "none"', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  Rotate: [
    { props: 'rotate', type: 'string', optional: true },
    { props: 'seconds', type: 'string | number', optional: true },
    { props: 'delay', type: 'string | number', optional: true },
    { props: 'loop', type: 'boolean', optional: true },
    { props: 'reverse', type: 'boolean', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  Scale: [
    { props: 'scale', type: 'string', optional: true },
    { props: 'seconds', type: 'string', optional: true },
    { props: 'loop', type: 'boolean', optional: true },
  ],
  TopLineList: [
    { props: 'col', type: 'string', optional: true },
    { props: 'justify', type: '"start" | "center" | "end"', optional: true },
    { props: 'item', type: '"stretch" | "start" | "center" | "end"', optional: true },
    { props: 'gap', type: 'string | number', optional: true },
    { props: 'lineGap', type: 'string | number', optional: true },
    { props: 'trimStart', type: 'boolean', optional: true },
    { props: 'trimEnd', type: 'boolean', optional: true },
    { props: 'mobile', type: '"lg" | "md" | "sm" | "xs" | "2xs" | "none"', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
    { props: 'maxWidth', type: 'string | number', optional: true },
    { props: 'center', type: 'boolean', optional: true },
  ],
  Transform: [
    { props: 'seconds', type: 'string | number', optional: true },
    { props: 'translate', type: 'string | number', optional: true },
    { props: 'rotate', type: 'string | number', optional: true },
    { props: 'scale', type: 'string | number', optional: true },
    { props: 'skew', type: 'string | number', optional: true },
    { props: 'delay', type: 'string | number', optional: true },
  ],
  Translate: [
    { props: 'seconds', type: 'string | number', optional: true },
    { props: 'translate', type: 'string | number', optional: true },
    { props: 'delay', type: 'string | number', optional: true },
  ],
  Container: [
    { props: 'maxWidth', type: 'string | number', optional: true },
    { props: 'center', type: 'boolean', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
  GridItem: [
    { props: 'col', type: 'string', optional: false },
    { props: 'wrap', type: 'boolean', optional: true },
    { props: 'flexReverse', type: 'boolean', optional: true },
    { props: 'mobile', type: '"3xl" | "2xl" | "xl" | "lg" | "md" | "sm" | "xs" | "2xs" | "none" | "inherit"', optional: true },
    { props: 'mobileItem', type: '"stretch" | "start" | "center" | "end" | "baseline"', optional: true },
    { props: 'mobileJustify', type: '"start" | "center" | "end" | "between" | "around" | "evenly" | "space-between" | "space-around" | "space-evenly"', optional: true },
    { props: 'mobileReverse', type: 'boolean', optional: true },
    { props: 'reverse', type: 'boolean', optional: true },
    { props: 'item', type: '"stretch" | "start" | "center" | "end" | "baseline"', optional: true },
    { props: 'justify', type: '"start" | "center" | "end" | "between" | "around" | "evenly" | "space-between" | "space-around" | "space-evenly"', optional: true },
    { props: 'gap', type: 'string | number', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
    { props: 'maxWidth', type: 'string | number', optional: true },
    { props: 'center', type: 'boolean', optional: true },
  ],
  LeftRight: [
    { props: 'mobile', type: '"2xl" | "xl" | "lg" | "md" | "sm" | "none"', optional: true },
    { props: 'mobileFit', type: 'boolean', optional: true },
    { props: 'overlay', type: 'string', optional: true },
    { props: 'contentWidth', type: 'string', optional: true },
    { props: 'contentDirection', type: '"inherit" | "ltr" | "rtl"', optional: true },
    { props: 'wrap', type: 'boolean', optional: true },
    { props: 'flexReverse', type: 'boolean', optional: true },
    { props: 'mobileItem', type: '"stretch" | "start" | "center" | "end" | "baseline"', optional: true },
    { props: 'mobileJustify', type: '"start" | "center" | "end" | "between" | "around" | "evenly" | "space-between" | "space-around" | "space-evenly"', optional: true },
    { props: 'mobileReverse', type: 'boolean', optional: true },
    { props: 'reverse', type: 'boolean', optional: true },
    { props: 'item', type: '"stretch" | "start" | "center" | "end" | "baseline"', optional: true },
    { props: 'justify', type: '"start" | "center" | "end" | "between" | "around" | "evenly" | "space-between" | "space-around" | "space-evenly"', optional: true },
    { props: 'gap', type: 'string | number', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
    { props: 'maxWidth', type: 'string | number', optional: true },
    { props: 'center', type: 'boolean', optional: true },
  ],
  SidePadding: [
    { props: 'mobile', type: '"2xl" | "xl" | "lg" | "md" | "none"', optional: true },
    { props: 'mobileFill', type: 'boolean', optional: true },
    { props: 'maxWidthStart', type: 'string | number', optional: true },
    { props: 'maxWidthEnd', type: 'string | number', optional: true },
    { props: 'marginBlock', type: 'string | number', optional: true },
    { props: 'paddingBlock', type: 'string | number', optional: true },
    { props: 'paddingInline', type: 'string | number', optional: true },
    { props: 'minPaddingInline', type: 'string | number', optional: true },
    { props: 'aside', type: '"none" | "start" | "end"', optional: true },
    { props: 'id', type: 'string', optional: true },
    { props: 'class', type: 'string | string[]', optional: true },
    { props: 'style', type: 'Record<string, any>', optional: true },
    { props: 'element', type: 'string', optional: true },
  ],
}
